import { AlertTriangle } from "lucide-react";

const Disclaimer = () => {
  return (
    <section className="py-16 bg-accent/30 border-y border-accent">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <div className="flex gap-4 items-start">
            <div className="flex-shrink-0">
              <div className="w-12 h-12 rounded-full bg-accent flex items-center justify-center">
                <AlertTriangle className="w-6 h-6 text-accent-foreground" />
              </div>
            </div>
            <div>
              <h3 className="text-xl font-bold mb-3 text-foreground">Important Medical Disclaimer</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                DermTrack is an AI-powered informational tool designed to help you track and understand your eczema patterns. 
                <strong className="text-foreground"> It is not a medical device and does not provide medical advice, diagnosis, or treatment.</strong>
              </p>
              <p className="text-muted-foreground leading-relaxed">
                All recommendations and insights are generated by artificial intelligence and should be reviewed with your healthcare provider. 
                Always consult a board-certified dermatologist before making changes to your treatment regimen or if you experience severe symptoms.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
